name: actionlint

# See: https://github.com/rhysd/actionlint

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  actionlint:
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.19

      - name: Install actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12
      - name: Run actionlint
        run: actionlint -color
