name: golangci-lint

on:
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  golangci-lint:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests
    runs-on: windows-latest
    steps:

      - name: Harden runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit # Audit network and disk activity

      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: 1.26
      
      - name: Run golangci-lint
        uses: step-security/golangci-lint-action@ce3368d2f0a15c79206a120861e3f847c8beb466 # v9.2.1
        with:
          skip-pkg-cache: true
      
      # Re-run golangci-lint as a workaround for https://github.com/golangci/golangci-lint-action/issues/362
      # to ensure that errors are reported.
      - name: Run golangci-lint again
        if: ${{ always() }}
        run: golangci-lint run
      
      - name: govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@19b0bb6a272792b9afa8a6983c3e9b9a1816947f # v1.6.0
          govulncheck ./...
